import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createOrbitServer } from "../build/server.js";
import { OrbitV3Client } from "../build/orbit-api.js";
import { profileOutputSchema } from "../build/output-schemas.js";

// Complete synthetic REST response generated by the API renderer, also used in
// the API docs. No production profiles or live API calls are involved.
const body = JSON.parse(readFileSync(new URL("./fixtures/profile-markdown.json", import.meta.url), "utf8"));
const billing = body.billing;

async function withMcp(responseBody, run, status = 200) {
  const originalFetch = globalThis.fetch;
  const calls = [];
  globalThis.fetch = async (url, init) => {
    calls.push({ url: String(url), init });
    return new Response(JSON.stringify(responseBody), { status });
  };
  const server = createOrbitServer("synthetic-key");
  const client = new Client({ name: "markdown-test", version: "1" });
  const [ct, st] = InMemoryTransport.createLinkedPair();
  try {
    await Promise.all([server.connect(st), client.connect(ct)]);
    await client.listTools();
    await run(client, calls);
  } finally {
    globalThis.fetch = originalFetch;
    await Promise.all([client.close(), server.close()]);
  }
}

test("get_profile advertises Markdown and returns real text blocks plus the intact package and billing", async () => {
  assert.equal(body.markdown.entrypoint, "USER.md");
  assert.equal(body.markdown.manifest.length, 8);
  assert.equal(Object.keys(body.markdown.files).length, 8);
  assert.deepEqual(new Set(body.markdown.manifest.map(file => file.status)), new Set(["available"]));
  assert(body.markdown.files["USER.md"].length <= 4000);
  assert(!Object.hasOwn(body.markdown.files, "profile/videos.md"));
  await withMcp(body, async (client, calls) => {
    const { tools } = await client.listTools();
    const tool = tools.find(tool => tool.name === "get_profile");
    assert.deepEqual(tool.inputSchema.properties.format.enum, ["json", "markdown"]);
    assert.equal(tool.outputSchema.type, "object");
    assert.ok(tool.outputSchema.properties.markdown);
    const result = await client.callTool({ name: "get_profile", arguments: { profile_id: "alias/with space", format: "markdown" } });
    assert.notEqual(result.isError, true);
    assert.deepEqual(result.structuredContent, body);
    assert.deepEqual(profileOutputSchema.parse(result.structuredContent), body);
    assert.deepEqual(JSON.parse(result.content[0].text), { entrypoint: body.markdown.entrypoint, manifest: body.markdown.manifest });
    assert(!result.content.some(block => block.text.includes(body.profile_id)));
    assert(!result.content[0].text.includes("generation_level"));
    assert(!result.content[0].text.includes("billing"));
    assert.equal(result.content.length, body.markdown.manifest.length + 1);
    for (let i = 0; i < body.markdown.manifest.length; i++) {
      const path = body.markdown.manifest[i].path;
      assert.equal(result.content[i + 1].text, `File: ${path}\n\n${body.markdown.files[path]}`);
    }
    assert.equal(calls.length, 1);
    assert.match(calls[0].url, /\/v3\/enrich\/alias%2Fwith%20space\?format=markdown$/);
    assert.equal(calls[0].init.headers.Authorization, "Bearer synthetic-key");
    assert.match(calls[0].init.headers["Idempotency-Key"], /^[0-9a-f-]{36}$/);
    assert.equal(calls[0].init.method, undefined);
  });
});

test("default and explicit JSON retain the same text, structured content, and URL", async () => {
  const json = { profile_id: "canonical", generation_level: 2, profile: { sections: { socials: { items: [] } } }, billing };
  await withMcp(json, async (client, calls) => {
    for (const args of [{ profile_id: "canonical" }, { profile_id: "canonical", format: "json" }]) {
      const result = await client.callTool({ name: "get_profile", arguments: args });
      assert.deepEqual(result.structuredContent, json);
      assert.deepEqual(JSON.parse(result.content[0].text), json);
      assert.equal(result.content.length, 1);
    }
    assert(calls.every(call => call.url.endsWith("/v3/enrich/canonical")));
    assert.notEqual(calls[0].init.headers["Idempotency-Key"], calls[1].init.headers["Idempotency-Key"]);
  });
});

test("Markdown read retries preserve one billing key and never search or regenerate", async () => {
  const calls = [];
  const responses = [503, 429, 200];
  const client = new OrbitV3Client({ apiKey: "synthetic", baseUrl: "https://orbit.test", sleepImpl: async () => {}, fetchImpl: async (url, init) => {
    calls.push({ url: String(url), init });
    const status = responses.shift();
    return new Response(JSON.stringify(status === 200 ? body : { error: "retry" }), { status, headers: { "retry-after": "0" } });
  } });
  assert.deepEqual(await client.getProfile("canonical", "markdown"), body);
  assert.equal(calls.length, 3);
  assert(calls.every(call => call.url === calls[0].url && call.init.headers["Idempotency-Key"] === calls[0].init.headers["Idempotency-Key"] && !call.init.body && !call.init.method));
});

for (const status of [401, 403, 402]) {
  test(`Markdown preserves HTTP ${status} denial as a text-only tool error`, async () => {
    await withMcp({ error: { code: "denied", message: "private-upstream-marker" } }, async (client, calls) => {
      const result = await client.callTool({ name: "get_profile", arguments: { profile_id: "canonical", format: "markdown" } });
      assert.equal(result.isError, true);
      assert.equal(result.structuredContent, undefined);
      assert.equal(calls.length, 1);
      assert.doesNotMatch(result.content[0].text, /private-upstream-marker/);
    }, status);
  });
}

test("a sparse root-only package remains usable as text with no empty section placeholders", async () => {
  const sparse = { ...body, markdown: { ...body.markdown, manifest: body.markdown.manifest.slice(0, 1), files: { "USER.md": "# User Profile\n\nNo public personal context is available.\n" } } };
  await withMcp(sparse, async client => {
    const result = await client.callTool({ name: "get_profile", arguments: { profile_id: "sparse", format: "markdown" } });
    assert.notEqual(result.isError, true);
    assert.deepEqual(result.structuredContent, sparse);
    assert.equal(result.content.length, 2);
    assert.equal(result.content[1].text, `File: USER.md\n\n${sparse.markdown.files["USER.md"]}`);
  });
});

for (const corrupt of [
  ...["profile/appearance.md", "profile/videos.md", "profile/connections.md"].map(path => ({ ...body, markdown: { ...body.markdown, manifest: [...body.markdown.manifest, { path, title: "Unsupported", status: "available" }], files: { ...body.markdown.files, [path]: "# Unsupported\n\nprivate-upstream-marker\n" } } })),
  { ...body, markdown: { ...body.markdown, entrypoint: "user.md" } },
  { ...body, markdown: { ...body.markdown, files: { ...body.markdown.files, "USER.md": "x".repeat(4001) } } },
  { ...body, markdown: { ...body.markdown, manifest: body.markdown.manifest.slice(1) } },
  { ...body, markdown: { ...body.markdown, manifest: body.markdown.manifest.map((file, i) => i === 1 ? { ...file, status: "empty" } : file) } },
  { ...body, markdown: { ...body.markdown, manifest: body.markdown.manifest.map(file => file.path === "profile/education.md" ? { ...file, path: "profile/unknown.md" } : file), files: Object.fromEntries(Object.entries(body.markdown.files).map(([path, text]) => [path === "profile/education.md" ? "profile/unknown.md" : path, text])) } },
  { ...body, markdown: { ...body.markdown, manifest: [{ path: "../escape.md", title: "Escape", status: "available" }] } },
  { ...body, markdown: { ...body.markdown, files: { "USER.md": "private-upstream-marker" } } },
  { ...body, markdown: { ...body.markdown, manifest: [...body.markdown.manifest, body.markdown.manifest[0]] } },
  { ...body, markdown: { ...body.markdown, files: { ...body.markdown.files, "extra.md": "private-upstream-marker" } } },
  { profile_id: "canonical", generation_level: 2, profile: {} },
]) {
  test("malformed or mismatched upstream Markdown is rejected without publishing text", async () => {
    await withMcp(corrupt, async client => {
      const result = await client.callTool({ name: "get_profile", arguments: { profile_id: "canonical", format: "markdown" } });
      assert.equal(result.isError, true);
      assert.equal(result.structuredContent, undefined);
      assert.match(result.content[0].text, /invalid Markdown profile package/);
      assert.doesNotMatch(result.content[0].text, /private-upstream-marker/);
    });
  });
}

test("invalid format fails input validation before any API call", async () => {
  await withMcp(body, async (client, calls) => {
    const result = await client.callTool({ name: "get_profile", arguments: { profile_id: "canonical", format: "md" } });
    assert.equal(result.isError, true);
    assert.equal(calls.length, 0);
  });
});
